cdef extern void initalpm()
cdef extern void initdatabase()
cdef extern void initgroup()
cdef extern void initpackage()
cdef extern void inittransaction()

initpackage()
initgroup()
initdatabase()
inittransaction()
initalpm()
